language: cpp

os: osx

branches:
    only:
        - master
        
env:
    matrix:
        - CONFIG=-release
        
install:
    brew update > /dev/null
      && brew install qt
      && chmod -R 755 /usr/local/opt/qt/*
      ;
    
