language: cpp

os: osx

compiler:
  - gcc
  - clang

branches:
  only:
    - master
        
env:
  global:
    - CODECOV_TOKEN="00f5e9e6-630b-491b-937c-c81c3f316480"
  matrix:
    - CONFIG=-release
        
install:
  brew install qt
    && chmod -R 755 /usr/local/opt/qt/*
    ;

before_script:
  - mkdir release
  - cd release
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . # make

script: make

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
