language: cpp

os: osx

compiler:
  - gcc
  - clang

branches:
  only:
    - master
        
env:
  matrix:
    - CONFIG=-release
        
install:
  brew install qt
    && chmod -R 755 /usr/local/opt/qt/*
    ;

before_script:
  - mkdir release
  - cd release
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . # make
  - ctest .         # make test

script: make && make test